spring.application.name=Stardew
spring.datasource.url=jdbc:postgresql://localhost:5432/stardew_valley
spring.datasource.username=postgres
spring.datasource.password=Nf101308!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port = 2020